<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
        <IsPackable>False</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Diagnostics" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="Avalonia.ReactiveUI" />
        <PackageReference Include="Prism.Avalonia" />
        <PackageReference Include="Prism.DryIoc.Avalonia" />
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Modules\ModuleA\ModuleA.csproj" />
        <ProjectReference Include="..\Modules\ModuleB\ModuleB.csproj" />
        <ProjectReference Include="..\Modules\ModuleC\ModuleC.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Language.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Language.resx</DependentUpon>
        </Compile>
        <EmbeddedResource Update="Properties\Language.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Language.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
</Project>