<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <IsPackable>False</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Prism.Avalonia" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\src\DynamicLocalizationUI.Avalonia\DynamicLocalizationUI.Avalonia.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Language.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Language.resx</DependentUpon>
        </Compile>
        <EmbeddedResource Update="Properties\Language.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Language.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>