<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1;net461;net6.0</TargetFrameworks>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);NU5128</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>DynamicLocalizationUI.Avalonia</PackageId>
        <Description>Dynamic runtime localization in the Avalonia application.</Description>
        <PackageTags>Avalonia;Localization;DynamicLocalization;Control;Xaml;Managed;C#"</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="All" />
    </ItemGroup>

    <Import Project="..\..\build\SignAssembly.props" />
    <Import Project="..\..\build\SourceLink.props" />
</Project>